### ISSUE TITLE
Shippable code badge is showing as not shippable - what broke?

### ISSUE THREAD

**Issue by ianakelly** [DevTestSolutions/TestDoubles#7]
Looks like the shippable build is broken since rev 17?  Is there a fix coming soon?

**Comment by rraheja** [comment]
The issue is with npm authentication. @sid11693 is looking into the resolution and will post an update shortly. Just to clarify, the docker repo still works so its the badge from Shippable that shows unshippable.

**Comment by sid11693** [comment]
Npm versioning issue. Resolved.
